(() => {
'use strict';
const data=window.DungeonsGameIcons,q=s=>document.querySelector(s),h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let group='gear',search='';
const labels={gear:'Eşyalar',enchantment:'Büyüler',effect:'Etkiler',skin:'Kostümler',cosmetic:'Kozmetikler',currency:'Kaynaklar',ui:'Arayüz'};
function category(e){const k=String(e.kind).toLowerCase();if(k.includes('enchant'))return 'enchantment';if(k.includes('effect'))return 'effect';if(k.includes('skin'))return 'skin';if(k.includes('currency'))return 'currency';if(k==='ui')return 'ui';if(k.includes('cosmetic')||k.includes('cape')||k.includes('pet'))return 'cosmetic';return 'gear'}
function draw(){if(!data)return;const groups=[...new Set(data.entries.map(category))];q('#catalog-filters').innerHTML=groups.map(g=>`<button data-catalog-group="${g}" class="${g===group?'active':''}">${labels[g]||g}</button>`).join('');const seen=new Set(),entries=data.entries.filter(e=>{if(category(e)!==group||![e.name,e.tag,e.category].join(' ').toLocaleLowerCase('tr').includes(search))return false;const k=group==='effect'?e.assetId+' '+e.name:e.tag||e.sourcePage+' '+e.name;if(seen.has(k))return false;seen.add(k);return true});q('#catalog-count').textContent=entries.length+' görsel';q('#catalog-grid').innerHTML=entries.map(e=>{const a=data.assets[e.assetId];return `<article class="catalog-card ${e.nativeFields?.unique?'unique':''}">${a?`<img loading="lazy" src="${a.dataUrl}" alt="${h(e.name)} — Minecraft Dungeons II ikonu">`:'<div class="icon-missing">Görsel bulunamadı</div>'}<strong>${h(e.name)}</strong><small>${h(e.tag||'Katalog görseli · Kayıt kimliği eşlenmedi')}</small></article>`}).join('')||'<p class="muted">Aramana uyan görsel bulunamadı.</p>';q('#catalog-coverage').textContent=`${Object.keys(data.assets).length} özgün ikon / görsel. Kaynakta eşleşen oyun kimlikleri kullanılır; görseller pakete gömülüdür ve internet gerekmez.`;}
q('#catalog-search').addEventListener('input',e=>{search=e.target.value.toLocaleLowerCase('tr');draw()});document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.catalogGroup){group=b.dataset.catalogGroup;draw()}});window.DungeonsCatalogue={draw};draw();
})();
